// <auto-generated />
using System;
using BlueSquares.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlueSquares.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlueSquares.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId", "WhatsAppNumber");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BlueSquares.Models.EmailSubscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("EmailSubscribers");
                });

            modelBuilder.Entity("BlueSquares.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastReminderSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("PaymentRefCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text");

                    b.Property<string>("PaymentTransactionId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PromisedPaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PromisedPaymentNote")
                        .HasColumnType("text");

                    b.Property<Guid?>("RecurringInvoiceScheduleId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReminderCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DueDate");

                    b.HasIndex("InvoiceNumber");

                    b.HasIndex("RecurringInvoiceScheduleId");

                    b.HasIndex("MerchantId", "Status");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("BlueSquares.Models.InvoiceLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLineItems");
                });

            modelBuilder.Entity("BlueSquares.Models.InvoiceQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("MerchantResponse")
                        .HasColumnType("text");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId", "IsResolved");

                    b.ToTable("InvoiceQueries");
                });

            modelBuilder.Entity("BlueSquares.Models.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountHolderName")
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<bool>("AutoRemindersEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("BankBic")
                        .HasColumnType("text");

                    b.Property<string>("BankIban")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<string>("BranchCode")
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DefaultInvoiceFooter")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<bool>("OzowEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("OzowPrivateKey")
                        .HasColumnType("text");

                    b.Property<string>("OzowSiteCode")
                        .HasColumnType("text");

                    b.Property<bool>("PayFastEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PayFastMerchantId")
                        .HasColumnType("text");

                    b.Property<string>("PayFastMerchantKey")
                        .HasColumnType("text");

                    b.Property<string>("PayPalClientId")
                        .HasColumnType("text");

                    b.Property<string>("PayPalClientSecret")
                        .HasColumnType("text");

                    b.Property<bool>("PayPalEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("PaystackEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PaystackPublicKey")
                        .HasColumnType("text");

                    b.Property<string>("PaystackSecretKey")
                        .HasColumnType("text");

                    b.Property<string>("PaystackSubscriptionCode")
                        .HasColumnType("text");

                    b.Property<string>("QuickBooksAccessToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("QuickBooksConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("QuickBooksEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("QuickBooksEnvironment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("QuickBooksLastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuickBooksRealmId")
                        .HasColumnType("text");

                    b.Property<string>("QuickBooksRefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("QuickBooksTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("StatementsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("StripeEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("StripePublishableKey")
                        .HasColumnType("text");

                    b.Property<string>("StripeSecretKey")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubscriptionExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TrialStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("XeroAccessToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("XeroConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("XeroEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("XeroLastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("XeroRefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("XeroTenantId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("XeroTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("BlueSquares.Models.RecurringInvoiceLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("RecurringInvoiceScheduleId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RecurringInvoiceScheduleId");

                    b.ToTable("RecurringInvoiceLineItems");
                });

            modelBuilder.Entity("BlueSquares.Models.RecurringInvoiceSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoSendEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoSendWhatsApp")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("integer");

                    b.Property<int>("DueDaysAfterIssue")
                        .HasColumnType("integer");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastGeneratedInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastRunDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("NextRunDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("LastGeneratedInvoiceId");

                    b.HasIndex("MerchantId", "IsActive", "NextRunDate");

                    b.ToTable("RecurringInvoiceSchedules");
                });

            modelBuilder.Entity("BlueSquares.Models.ReminderSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DaysAfterDue")
                        .HasColumnType("integer");

                    b.Property<int>("DaysBeforeDue")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("ReminderSchedules");
                });

            modelBuilder.Entity("BlueSquares.Models.Client", b =>
                {
                    b.HasOne("BlueSquares.Models.Merchant", "Merchant")
                        .WithMany("Clients")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("BlueSquares.Models.Invoice", b =>
                {
                    b.HasOne("BlueSquares.Models.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueSquares.Models.Merchant", "Merchant")
                        .WithMany("Invoices")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlueSquares.Models.RecurringInvoiceSchedule", "RecurringInvoiceSchedule")
                        .WithMany()
                        .HasForeignKey("RecurringInvoiceScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Merchant");

                    b.Navigation("RecurringInvoiceSchedule");
                });

            modelBuilder.Entity("BlueSquares.Models.InvoiceLineItem", b =>
                {
                    b.HasOne("BlueSquares.Models.Invoice", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("BlueSquares.Models.InvoiceQuery", b =>
                {
                    b.HasOne("BlueSquares.Models.Invoice", "Invoice")
                        .WithMany("Queries")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("BlueSquares.Models.RecurringInvoiceLineItem", b =>
                {
                    b.HasOne("BlueSquares.Models.RecurringInvoiceSchedule", "RecurringInvoiceSchedule")
                        .WithMany("LineItems")
                        .HasForeignKey("RecurringInvoiceScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecurringInvoiceSchedule");
                });

            modelBuilder.Entity("BlueSquares.Models.RecurringInvoiceSchedule", b =>
                {
                    b.HasOne("BlueSquares.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueSquares.Models.Invoice", "LastGeneratedInvoice")
                        .WithMany()
                        .HasForeignKey("LastGeneratedInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlueSquares.Models.Merchant", "Merchant")
                        .WithMany("RecurringInvoiceSchedules")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("LastGeneratedInvoice");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("BlueSquares.Models.ReminderSchedule", b =>
                {
                    b.HasOne("BlueSquares.Models.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("BlueSquares.Models.Client", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("BlueSquares.Models.Invoice", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("Queries");
                });

            modelBuilder.Entity("BlueSquares.Models.Merchant", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Invoices");

                    b.Navigation("RecurringInvoiceSchedules");
                });

            modelBuilder.Entity("BlueSquares.Models.RecurringInvoiceSchedule", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
